groups:
- name: nodeapp
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: "critical"
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'

  - alert: RequestLimit
    expr: total_http_request_count != 0 and total_http_request_count%5 == 0
    for: 10s
    labels:
      severity: "critical"
    annotations:
      title: '5 New requests received'
      description: '5 New HTTP requests received for node-app'
